import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import CreateRoom from "../components/CreateRoom";
import styles from "../styles/Home.module.css";
import { signIn, signOut, useSession } from "next-auth/react";
import { FaGoogle, FaMicrosoft, FaSignInAlt } from "react-icons/fa";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (status === "loading") {
    return <p>Loading...</p>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {!session && (
          <button
            className={styles.primaryButtonAuth0}
            onClick={() => signIn("auth0")}
          >
            <div className={styles.divRow}>
              <h4>Escolha uma conta para continuar</h4>
            </div>
          </button>
        )}
        {session && <CreateRoom user={session.user} />}
      </main>
    </div>
  );
};

export default Home;
